# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('describe', models.TextField()),
                ('start', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('receiver', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
